### ISSUE TITLE
Where is the Jackett UI?

### ISSUE THREAD

**Issue by laichiaheng** [qbittorrent/search-plugins#102]
Jackett API Key (you can find it on top of Jackett UI)
Where is the UI?
Do I need to install jackett from AUR for qbittorrent?
Do I need to start the jackett.service for it?

**Comment by laichiaheng** [comment]
Nothing, I just realize that I need to open my web browser and input the `127.0.0.1:9117` in URL, and add them manually.

**Comment by rootkea** [comment]
When I try to visit `http://127.0.0.1:9117` the browser says "Unable to connect". What do I put as a value of `api_key` field in jackett.json?
```
$ cat ~/.local/share/data/qBittorrent/nova3/engines/jackett.json
{
    "api_key": "YOUR_API_KEY_HERE",
    "tracker_first": false,
    "url": "http://127.0.0.1:9117"
}
$
``` 
BTW, I'm using QbitTorrent 4.1.5 (64-bit) on Debian 10.

**Comment by laichiaheng** [comment]
@rootkea You need to enable the jackett service first.
`sudo systemctl start jackett.service`
If you want to start the service everytime.
`sudo systemctl enable jackett.service`
The key is in here:
![2019-08-08 21-08-34 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/62705957-1590a980-ba21-11e9-956e-bdc96d75b631.png)

**Comment by rootkea** [comment]
This is weird.

If one needs to install Jackett explicitly then how is Jacket enabled by default in QbitTorrent fresh install?

If we really want to enable Jackett by default then we should make Jackett as a dependency to QbitTorrent.

But, it looks like Jacket is not in official stable Debian repos. Maybe we should disable Jackett by default since the required package Jackett isn't installed when QbitTorrent is installed and in some instances (like Debian) it's not even in the distro repos to install.

**Comment by ngosang** [comment]
@rootkea I'm going to disable Jackett by default, but I have to change several thinks first to make it possible. Will be fixed by the end of the year.

**Comment by p060477** [comment]
so the only way to have the api key is to install jackett..??

**Comment by FranciscoPombal** [comment]
> so the only way to have the api key is to install jackett..??

Of course.
