### ISSUE TITLE
All the plugins here cannot be installed

### ISSUE THREAD

**Issue by luanshixiao** [qbittorrent/search-plugins#142]
I have already installed qbittorrent 4.2.5.12 and Python3.
However,all the plugins here cannot be installed.
It showes the plugin is unsupported.
But unofficial search plugins(e.g. kickass) can be installed correctly.
What‘s wrong?

**Comment by Puled** [comment]
Me too, I'm using qBittorrent v4.2.5. what's wrong?

**Comment by amaforlife** [comment]
same issue here

**Comment by p060477** [comment]
hi!
i've lots of problems with the jackett plugin..see these:
https://github.com/Jackett/Jackett/issues/9100#issuecomment-654420592

**Comment by luanshixiao** [comment]
> hi!
> i've lots of problems with the jackett plugin..see these:
> [Jackett/Jackett#9100 (comment)](https://github.com/Jackett/Jackett/issues/9100#issuecomment-654420592)

I see,so we need to install jackett first in order to install the plugins here?
Where can I find a tutorial for jackett?

**Comment by Puled** [comment]
> hi!
> i've lots of problems with the jackett plugin..see these:
> [Jackett/Jackett#9100 (comment)](https://github.com/Jackett/Jackett/issues/9100#issuecomment-654420592)

Some plugins (torent galaxy) can now be added to qBittorrent after installation of Jackett, but some (ali and kickass) still can't be added. 
 And, I think inistalling plugins on previous versions doesn't need Jackett.

**Comment by p060477** [comment]
but you have INSTALLED jackett app on yr pc..??..so you have it in c programs etcc…
and you are running in services.msc its jackett service..??
and IF so you eventually stated that even some search plugins are still not working at all..??
i really think that here who has the responsability of the qbittorent search plug ins have to make a real CLARIFICATION...
because after all these bugs and issues some one could be suggested to migrate to another torrent client…
and moreover NOT to install jackett search plugin at all..
rreally hope someone skilled will be able to usefully reply ..
thxs so much Pulled for yr precious witness
regards

**Comment by p060477** [comment]
which is -ali-...?? is a searchplugin torrent for qbittorrent..?
if yes where to see it..??

**Comment by luanshixiao** [comment]
> > hi!
> > i've lots of problems with the jackett plugin..see these:
> > [Jackett/Jackett#9100 (comment)](https://github.com/Jackett/Jackett/issues/9100#issuecomment-654420592)
> 
> Some plugins (torent galaxy) can now be added to qBittorrent after installation of Jackett, but some (ali and kickass) still can't be added.
> And, I think inistalling plugins on previous versions doesn't need Jackett.

Emmm,my qbittorrent can install the kickass without jackett.

**Comment by luanshixiao** [comment]
> but you have INSTALLED jackett app on yr pc..??..so you have it in c programs etcc…
> and you are running in services.msc its jackett service..??
> and IF so you eventually stated that even some search plugins are still not working at all..??
> i really think that here who has the responsability of the qbittorent search plug ins have to make a real CLARIFICATION...
> because after all these bugs and issues some one could be suggested to migrate to another torrent client…
> and moreover NOT to install jackett search plugin at all..
> rreally hope someone skilled will be able to usefully reply ..
> thxs so much Pulled for yr precious witness
> regards

I haven't figured out how to install and use jackett, and I use win10.

**Comment by p060477** [comment]
..me too...and in the github search plugins pages there is really NOT clearly written that we have to...

**Comment by Puled** [comment]
See Issue https://github.com/qbittorrent/search-plugins/issues/121#issue-536653344

Jackett is like a completely new software that works independently from all the plugins.

ngosang, a member of qBittorrent and the maintainer of plugins, said they're going to give up all these plugins, because Jackett alone is good enough already, and it has included a lot of torrent search sites (indexers).

So I think qBittorrent wants us to ditch plugins and use [Jackett](https://github.com/Jackett/Jackett#installation-on-windows) instead.

**Comment by p060477** [comment]
hi Puled

many thxs again for yr precious witness
for me it will be a very bad new cuase i really do NOT want to -install- Jackett
and moreover i really do not want to have it managing the ALL search project at all…
so if this is the aim of qbittorent dev i really will migrate to another client and i use
,as search plug, a very smart tool
Bitche
which is really PORTABLE
NO INSTALL
take care
regards

**Comment by luanshixiao** [comment]
> See Issue [#121 (comment)](https://github.com/qbittorrent/search-plugins/issues/121#issue-536653344)
> 
> Jackett is like a completely new software that works independently from all the plugins.
> 
> ngosang, a member of qBittorrent and the maintainer of plugins, said they're going to give up all these plugins, because Jackett alone is good enough already, and it has included a lot of torrent search sites (indexers).
> 
> So I think qBittorrent wants us to ditch plugins and use [Jackett](https://github.com/Jackett/Jackett#installation-on-windows) instead.

get it,thx.

**Comment by p060477** [comment]
it is also my -strong- opinion…..

**Comment by ElricUK** [comment]
All very well saying use jackett, but the jackett plugin comes up unsupported as well (like the others). Is there any fix for this?
Tried on 4.1.x and 4.2.5, have python 3.6 installed.

**Comment by p060477** [comment]
cause they want you to INSTALL jackett on yr pc...
what a pity..
what a shame...
they will loose lots of users....
:(

**Comment by ElricUK** [comment]
I have the jackett service installed, I want to get the qbittorrent plugin added to interface with it?

**Comment by ngosang** [comment]
I just tested all plugins with qBittorrent v4.2.5 and Python 3.8.5 in Linux and Windows. All plugins can be installed and they are working.

Some considerations:
1. Jackett is an external program. You can install it or disable the Jackett plugin in qBittorrent. https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin
2. qBittorrent can work without Jackett. You have the official and unofficial qBittorrent plugins. I recommend Jackett because it's more up to date and it supports more than 500 sites.
3. When you install qBittorrent, the first time you open the search engine the official plugins (this repository) will be downloaded automatically, so you don't have to install them manually.
4. If you are having problems you can try to remove the plugins configuration folder. Close qBittorrent first.
* Windows: `%localappdata%\qBittorrent\nova3`
* Linux: `~/.local/share/data/qBittorrent/nova3`
* OS X: `~/Library/Application Support/qBittorrent/nova3`
