### ISSUE TITLE
Proposal for enhancement of CI for search plugins.

### ISSUE THREAD

**Issue by nindogo** [qbittorrent/search-plugins#155]
I would like to propose some changes to CI for search-plugins.

For now, I think, line lengths is what is tested for. Potentially with every change the following can be tested for:

1. Can the site be reached and a request made?
1. Does a response get produced?
1. If the response is known before hand, then a test could also be done on the response data to confirm that it is correct if not the previous test tells us that there is a response.

For proper test [nova2.py](https://github.com/qbittorrent/qBittorrent/raw/master/src/searchengine/nova3/nova2.py), [helpers.py](https://github.com/qbittorrent/qBittorrent/raw/master/src/searchengine/nova3/helpers.py), [novaprinter.py](https://github.com/qbittorrent/qBittorrent/raw/master/src/searchengine/nova3/novaprinter.py), etc may be needed to be able to run the tests end to end.

Please tell me what you think?

**Comment by ngosang** [comment]
That's the right way but there are some issues:
* Travis, Github Actions, Azure Pipelines... block external requests. Even if they were allowed, some torrent sites are blocked by ISPs..
* If one site is down I can't merge PRs (I can because I'm admin but that's not the point).
* Sites are only tested on new PRs. Will be more interesting to have nightly builds and alert the maintainers if something is wrong. Do it for unofficial plugins too. You don't need a big server, just a raspberry pi or something at home.

I have a couple of bash scripts to test all indexers in local from time to time.  If you want to do some of this, promote some unofficial plugins to official, etc I will review the PRs. As you know I'm not active maintaining this project. I'm working in Jackett and related projects.

**Comment by nindogo** [comment]
>... there are some issues:
> 
> * Travis, Github Actions, Azure Pipelines... block external requests. Even if they were allowed, some torrent sites are blocked by ISPs..

Did not know about the above. 

> * If one site is down I can't merge PRs (I can because I'm admin but that's not the point).
Noted.

> * Sites are only tested on new PRs. Will be more interesting to have nightly builds and alert the maintainers if something is wrong. Do it for unofficial plugins too. You don't need a big server, just a raspberry pi or something at home.

[Python's Package Authority](https://www.pypa.io/en/latest/) [moved](http://pyfound.blogspot.com/2020/11/pypi-receives-aws-credits-for-open.html) to [AWS credits](https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/) recently. Maybe as a torrent tool [qBittorrent/search-plugins](https://github.com/qbittorrent/search-plugins/) will not qualify but if there is someone with an official qBittorrent account they could [apply](https://aws.amazon.com/awscredits/). A build bot on there that could work daily and mail developers may achieve this. I am in Africa on slowish internet, and Windows box, don't trust it for running a build bot even for RaspberryPI.

> I have a couple of bash scripts to test all indexers in local from time to time. If you want to do some of this, promote some unofficial plugins to official, etc I will review the PRs. As you know I'm not active maintaining this project. I'm working in Jackett and related projects.

Noted.

**Comment by nindogo** [comment]
This may not be able to be implemented.
