### ISSUE TITLE
Question: Instructions appear incorrect for QBT v4.5.0

### ISSUE THREAD

**Issue by 101John** [qbittorrent/search-plugins#223]
macOS
QBT v 4.5.0 with LT2.0

I can't follow the instructions for Jackett at this wiki page:
https://github.com/qbittorrent/search-plugins/wiki/New-Torznab-search-engine

It looks as if they were updated today. Are these instructions only for Windows OS or a Master build/release?

I am still seeing "Search Plugins..." instead of "Indexers" with reference to installing what appear to be Python Plugins.

<img width="856" alt="Screen Shot 2023-01-22 at 10 44 26 AM" src="https://user-images.githubusercontent.com/9438406/213927866-fb467b31-f342-47f1-a096-0c4a5c177834.png">

**Contents of nova3**

nova3
__init__.py
__pycache__
helpers.cpython-310.pyc
novaprinter.cpython-310.pyc
socks.cpython-310.pyc
engines
__init__.py
__pycache__
eztv.ico
eztv.py
jackett.ico
jackett.json
jackett.py
legittorrents.py
limetorrents.ico
limetorrents.py
piratebay.ico
piratebay.py
rarbg.ico
rarbg.py
solidtorrents.py
torlock.py
torrentproject.ico
torrentproject.py
torrentscsv.py
helpers.py
nova2.py
nova2dl.py
novaprinter.py
sgmllib3.py
socks.py

**Comment by knw257** [comment]
It's unclear why this issue was closed. The wiki page is still incorrect - it seems qBt 5.0.2 no longer supports Torznab indexers, having opted for search plugins. Unfortunately, the Jackett plugin isn't nearly as useful as being able to add separate indexers to the search engine. Note: I'm using the qBittorrent-nox docker container, exclusively using the webUI, so this may be an issue. If so, it should be noted in the wiki

**Comment by Fred-Vatin** [comment]
I asked the same question in https://github.com/qbittorrent/search-plugins/issues/121#issuecomment-4062477379
